version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      # folder we do no want to replace because /node_modules is not created on our local machince. 
      # hence, if we do not write this line, /node_modules will be deleted inside the container.
      - /app/node_modules     # dir inside container   
      - ./frontend:/app       # dir on our local machine
  api:
    build: ./api
    restart: always
    ports:
      - '5555:5000'
    # This container will start only after mysql container is up
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./api:/app
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data:/var/lib/mysql 
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
  mysql_data: 